port_name: /dev/ttyUSB0
enable_receiving_sbus_messages: true
control_command_timeout: 0.5 # [s] (Must be larger than 'state_estimate_timeout' set in the 'flight_controller'!)
rc_timeout: 0.1 # [s]
mass: 0.865 # [kg]
disable_thrust_mapping: false
thrust_map_a: 6.91194111204e-06 # When updating the thrust mapping. also the voltage dependency mapping has to be updated!
thrust_map_b: 0.00754094874204
thrust_map_c: -6.01740637316
max_roll_rate: 804.0 # [deg/s] Maximum Roll rate that is set on the Flight Controller
max_pitch_rate: 804.0 # [deg/s] Maximum Pitch rate that is set on the Flight Controller
max_yaw_rate: 400.0 # [deg/s] Maximum Yaw rate that is set on the Flight Controller
max_roll_angle: 50 # [deg] Maximum roll angle when using angle control mode
max_pitch_angle: 50 # [deg] Maximum pitch angle when using angle control mode
alpha_vbat_filter: 0.01
perform_thrust_voltage_compensation: true
thrust_ratio_voltage_map_a: -0.17044342 # [1/V]
thrust_ratio_voltage_map_b: 3.10495276 # [-]
n_lipo_cells: 3 # [-]
